apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJsb2dpbjJhd3MuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImJHOW5hVzR5WVhkelFHZHZiMmRzWlM1amIyMDZRMjkzWW05NVFERT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
